/**
 * Schema drift detector and auto-repair migration generator.
 *
 * Compares the schema manifest (scripts/db/schema-manifest.mjs) against the
 * actual database and, if any columns are missing, generates a numbered
 * migration file in migrations/versions/ with the corrective SQL.
 *
 * Safety guarantees:
 *   - Only generates ADD COLUMN IF NOT EXISTS (additive, never destructive).
 *   - Never directly alters the database — writes a migration file for review.
 *   - Missing tables are reported but not auto-created (too risky without
 *     knowing the full constraint/index requirements).
 *   - Exits 1 when drift is found (blocks pre-push hook). Exits 0 when clean.
 *
 * Usage:
 *   node scripts/db/schema-drift.mjs            # check + generate if needed
 *   node scripts/db/schema-drift.mjs --check-only  # check only, no file write
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import {
  withDatabaseClient,
  listAvailableMigrations,
} from './migration-lib.mjs';
import {
  SCHEMA_MANIFEST,
  SCHEMA_ENUM_MANIFEST,
  REQUIRED_TABLES,
} from './schema-manifest.mjs';

const MIGRATIONS_DIR = path.resolve(process.cwd(), 'migrations/versions');

function parseFlag(argv, flag) {
  return argv.includes(flag);
}

async function getActualColumns(client, tableNames) {
  if (tableNames.length === 0) return new Map();

  const result = await client.query(
    `
      SELECT table_name, column_name
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = ANY($1::text[])
    `,
    [tableNames],
  );

  const actual = new Map();
  for (const row of result.rows) {
    if (!actual.has(row.table_name)) {
      actual.set(row.table_name, new Set());
    }
    actual.get(row.table_name).add(row.column_name);
  }
  return actual;
}

async function getActualTables(client) {
  const result = await client.query(`
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
  `);
  return new Set(result.rows.map((r) => r.table_name));
}

async function getActualEnumLabels(client, enumNames) {
  if (enumNames.length === 0) {
    return { labelsByEnum: new Map(), existingEnums: new Set() };
  }

  const result = await client.query(
    `
      SELECT
        format('%I.%I', n.nspname, t.typname) AS enum_name,
        e.enumlabel AS enum_label
      FROM pg_type t
      JOIN pg_namespace n ON n.oid = t.typnamespace
      LEFT JOIN pg_enum e ON e.enumtypid = t.oid
      WHERE t.typtype = 'e'
        AND format('%I.%I', n.nspname, t.typname) = ANY($1::text[])
      ORDER BY enum_name ASC, e.enumsortorder ASC
    `,
    [enumNames],
  );

  const labelsByEnum = new Map();
  const existingEnums = new Set();

  for (const row of result.rows) {
    const enumName = row.enum_name;
    existingEnums.add(enumName);
    if (!labelsByEnum.has(enumName)) {
      labelsByEnum.set(enumName, new Set());
    }
    if (row.enum_label) {
      labelsByEnum.get(enumName).add(row.enum_label);
    }
  }

  return { labelsByEnum, existingEnums };
}

function nextMigrationVersion(migrations) {
  if (migrations.length === 0) return '0001';
  const last = migrations[migrations.length - 1];
  const n = parseInt(last.version, 10) + 1;
  return String(n).padStart(4, '0');
}

function formatUpSql(byTable, missingEnumLabelsByType) {
  const date = new Date().toISOString().split('T')[0];
  const lines = [
    `-- Auto-generated schema drift repair: ${date}`,
    `-- Generated by: npm run db:schema:drift`,
    `-- Missing columns detected in the database.`,
    `-- Missing enum labels detected for managed enums.`,
    `-- All statements use ADD COLUMN IF NOT EXISTS (safe to re-run).`,
    `-- REVIEW before committing: verify types and defaults are correct.`,
    '',
    'BEGIN;',
    '',
  ];

  for (const [table, cols] of byTable) {
    lines.push(`ALTER TABLE IF EXISTS public.${table}`);
    const entries = [...cols];
    entries.forEach(({ column, definition }, i) => {
      const comma = i < entries.length - 1 ? ',' : ';';
      lines.push(`  ADD COLUMN IF NOT EXISTS ${column} ${definition}${comma}`);
    });
    lines.push('');
  }

  for (const [enumName, labels] of missingEnumLabelsByType) {
    lines.push(`-- Enum labels for ${enumName}`);
    lines.push('DO $$');
    lines.push('BEGIN');
    lines.push(`  IF to_regtype('${enumName}') IS NULL THEN`);
    lines.push(`    RAISE NOTICE 'Type ${enumName} does not exist; skipping.';`);
    lines.push('  ELSE');
    for (const label of labels) {
      const escapedLabel = label.replace(/'/g, "''");
      lines.push(`    ALTER TYPE ${enumName} ADD VALUE IF NOT EXISTS '${escapedLabel}';`);
    }
    lines.push('  END IF;');
    lines.push('END;');
    lines.push('$$;');
    lines.push('');
  }

  lines.push('COMMIT;');
  return lines.join('\n');
}

function formatDownSql(byTable, missingEnumLabelsByType) {
  const lines = [
    `-- Rollback for auto-generated schema drift repair.`,
    `-- NOTE: Enum label additions are forward-only and intentionally not removed here.`,
    '',
    'BEGIN;',
    '',
  ];

  for (const [table, cols] of byTable) {
    lines.push(`ALTER TABLE IF EXISTS public.${table}`);
    const entries = [...cols];
    entries.forEach(({ column }, i) => {
      const comma = i < entries.length - 1 ? ',' : ';';
      lines.push(`  DROP COLUMN IF EXISTS ${column}${comma}`);
    });
    lines.push('');
  }

  if (missingEnumLabelsByType.size > 0) {
    lines.push('-- Enum label rollback is intentionally a no-op.');
    lines.push('SELECT 1;');
    lines.push('');
  }

  lines.push('COMMIT;');
  return lines.join('\n');
}

async function run() {
  const checkOnly = parseFlag(process.argv, '--check-only');
  const tableNames = Object.keys(SCHEMA_MANIFEST);
  const enumNames = Object.keys(SCHEMA_ENUM_MANIFEST);

  let missingColumns;
  let missingTables;
  let missingEnumTypes;
  let missingEnumLabels;

  await withDatabaseClient(async (client) => {
    const [
      actualColumns,
      actualTables,
      { labelsByEnum: actualEnumLabels, existingEnums },
    ] = await Promise.all([
      getActualColumns(client, tableNames),
      getActualTables(client),
      getActualEnumLabels(client, enumNames),
    ]);

    // Find missing columns
    missingColumns = [];
    for (const [table, colMap] of Object.entries(SCHEMA_MANIFEST)) {
      const actual = actualColumns.get(table) ?? new Set();
      for (const [column, definition] of Object.entries(colMap)) {
        if (!actual.has(column)) {
          missingColumns.push({ table, column, definition });
        }
      }
    }

    // Find missing tables (report only — not auto-created)
    missingTables = REQUIRED_TABLES.filter((t) => !actualTables.has(t));

    // Find missing enums (report only — not auto-created)
    missingEnumTypes = enumNames.filter((enumName) => !existingEnums.has(enumName));

    // Find missing enum labels for existing enums
    missingEnumLabels = [];
    for (const enumName of enumNames) {
      if (missingEnumTypes.includes(enumName)) continue;
      const actualLabels = actualEnumLabels.get(enumName) ?? new Set();
      const requiredLabels = SCHEMA_ENUM_MANIFEST[enumName] ?? [];
      for (const label of requiredLabels) {
        if (!actualLabels.has(label)) {
          missingEnumLabels.push({ enumName, label });
        }
      }
    }
  });

  const hasMissingColumns = missingColumns.length > 0;
  const hasMissingTables = missingTables.length > 0;
  const hasMissingEnumTypes = missingEnumTypes.length > 0;
  const hasMissingEnumLabels = missingEnumLabels.length > 0;

  if (!hasMissingColumns && !hasMissingTables && !hasMissingEnumTypes && !hasMissingEnumLabels) {
    console.log('✅ Schema is up to date. No drift detected.');
    return;
  }

  // Report missing tables
  if (hasMissingTables) {
    console.error('\n⚠️  Missing tables (not auto-repaired — run migrations manually):');
    for (const table of missingTables) {
      console.error(`   - public.${table}`);
    }
  }

  if (hasMissingEnumTypes) {
    console.error('\n⚠️  Missing enum types (not auto-repaired — run migrations manually):');
    for (const enumName of missingEnumTypes) {
      console.error(`   - ${enumName}`);
    }
  }

  if (hasMissingEnumLabels) {
    const enumLabelMap = new Map();
    for (const { enumName, label } of missingEnumLabels) {
      if (!enumLabelMap.has(enumName)) enumLabelMap.set(enumName, []);
      enumLabelMap.get(enumName).push(label);
    }

    console.error(
      `\n❌ Enum drift: ${missingEnumLabels.length} missing enum label(s) across ${enumLabelMap.size} type(s):`,
    );
    for (const [enumName, labels] of enumLabelMap) {
      console.error(`\n   ${enumName}:`);
      for (const label of labels) {
        console.error(`     + ${label}`);
      }
    }
  }

  // Auto-generate migration for missing columns
  if (hasMissingColumns || hasMissingEnumLabels) {
    // Group by table, preserving order
    const byTable = new Map();
    for (const { table, column, definition } of missingColumns) {
      if (!byTable.has(table)) byTable.set(table, []);
      byTable.get(table).push({ column, definition });
    }

    if (hasMissingColumns) {
      console.error(
        `\n❌ Schema drift: ${missingColumns.length} missing column(s) across ${byTable.size} table(s):`,
      );
      for (const [table, cols] of byTable) {
        console.error(`\n   ${table}:`);
        for (const { column, definition } of cols) {
          console.error(`     + ${column}  (${definition})`);
        }
      }
    }

    // Group missing enum labels by type, preserving order
    const missingEnumLabelsByType = new Map();
    for (const { enumName, label } of missingEnumLabels) {
      if (!missingEnumLabelsByType.has(enumName)) {
        missingEnumLabelsByType.set(enumName, []);
      }
      missingEnumLabelsByType.get(enumName).push(label);
    }

    if (checkOnly) {
      console.error('\nRun without --check-only to auto-generate a repair migration.');
      process.exit(1);
    }

    // Write migration files
    const migrations = await listAvailableMigrations();
    const version = nextMigrationVersion(migrations);
    const name = 'auto_schema_drift';
    const upFile = path.join(MIGRATIONS_DIR, `${version}_${name}.up.sql`);
    const downFile = path.join(MIGRATIONS_DIR, `${version}_${name}.down.sql`);

    await fs.writeFile(upFile, formatUpSql(byTable, missingEnumLabelsByType));
    await fs.writeFile(downFile, formatDownSql(byTable, missingEnumLabelsByType));

    const relUp = path.relative(process.cwd(), upFile);
    const relDown = path.relative(process.cwd(), downFile);

    console.error('\n📄 Repair migration generated:');
    console.error(`   ${relUp}`);
    console.error(`   ${relDown}`);
    console.error('\n⚠️  NEXT STEPS:');
    console.error(`   1. Review the generated migration (check types and defaults)`);
    console.error(`   2. Commit both files:`);
    console.error(`      git add ${relUp} ${relDown}`);
    console.error(`      git commit -m "fix: repair schema drift"`);
    console.error(`   3. Push again`);
    console.error('');
    console.error(
      '   If the manifest is wrong (e.g. a column was intentionally removed),',
    );
    console.error('   update scripts/db/schema-manifest.mjs and delete the generated files.');
  }

  process.exit(1);
}

run().catch((error) => {
  console.error(
    `Schema drift check failed: ${error instanceof Error ? error.message : String(error)}`,
  );
  process.exit(1);
});
