import { defineArrayMember, defineField, defineType } from 'sanity';
import { ComposeIcon } from '@sanity/icons';

export const blogPost = defineType({
  name: 'blogPost',
  title: 'Blog Post',
  type: 'document',
  icon: ComposeIcon,
  description: 'Articles, guides, and resources for the blog.',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'metadata', title: 'Details' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'URL Path',
      type: 'slug',
      group: 'content',
      description: 'Auto-generated from the title. Used in the blog post URL.',
      options: { source: 'title' },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      description: 'A short summary shown on blog listing pages and social shares.',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover Image',
      type: 'image',
      group: 'content',
      description: 'Displayed at the top of the post and in previews.',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Alt text', type: 'string' })],
    }),
    defineField({
      name: 'body',
      title: 'Body',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({ type: 'block' })],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'publishedAt',
      title: 'Publish Date & Time',
      type: 'datetime',
      group: 'metadata',
      description: 'When this post goes live. Defaults to now.',
      initialValue: () => new Date().toISOString(),
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'isFeatured',
      title: 'Featured Post',
      description: 'Featured posts are highlighted on the blog page.',
      type: 'boolean',
      group: 'metadata',
      initialValue: false,
    }),
    defineField({
      name: 'readingTimeMinutes',
      title: 'Reading Time (minutes)',
      type: 'number',
      group: 'metadata',
      description: 'Estimated reading time shown to readers.',
      validation: (Rule) => Rule.min(1).max(120),
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      group: 'metadata',
      description: 'Categorise posts so visitors can filter content.',
      of: [defineArrayMember({ type: 'string' })],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'resourceUrl',
      title: 'External Resource URL',
      description: 'Link to an external resource referenced in the post.',
      type: 'url',
      group: 'metadata',
    }),
    defineField({
      name: 'resourceFile',
      title: 'Downloadable File',
      description: 'Attach a PDF, template, or other downloadable file.',
      type: 'file',
      group: 'metadata',
    }),
    defineField({
      name: 'publishDate',
      title: 'Publish Date (date only)',
      type: 'date',
      group: 'metadata',
      hidden: true,
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seoFields',
      group: 'seo',
    }),
  ],
  orderings: [
    {
      title: 'Published Date (Newest)',
      name: 'publishedDesc',
      by: [{ field: 'publishedAt', direction: 'desc' }],
    },
    {
      title: 'Title (A-Z)',
      name: 'titleAsc',
      by: [{ field: 'title', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'publishedAt',
      media: 'coverImage',
      featured: 'isFeatured',
    },
    prepare: ({ title, subtitle, media, featured }) => ({
      title: `${featured ? '* ' : ''}${title || 'Untitled Blog Post'}`,
      subtitle: subtitle ? new Date(subtitle).toLocaleDateString() : 'Draft',
      media,
    }),
  },
});
