import { defineArrayMember, defineField, defineType } from 'sanity';
import { EditIcon } from '@sanity/icons';
import { isSlugUniqueAcrossTypes } from './shared/slugValidation';

export const serviceItem = defineType({
  name: 'serviceItem',
  title: 'Service',
  type: 'document',
  icon: EditIcon,
  description: 'Services and products offered by Plenor Systems.',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'details', title: 'Details' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Service Name',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'URL Path',
      type: 'slug',
      group: 'content',
      description: 'Auto-generated from the title.',
      options: { source: 'title', isUnique: isSlugUniqueAcrossTypes },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      description: 'Short description shown on listing cards and previews.',
      type: 'text',
      rows: 3,
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      group: 'content',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Alt text', type: 'string' })],
    }),
    defineField({
      name: 'body',
      title: 'Full Description',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({ type: 'block' })],
    }),
    defineField({
      name: 'brochureFile',
      title: 'Brochure / Download',
      description: 'Attach a PDF brochure or spec sheet.',
      type: 'file',
      group: 'content',
    }),
    defineField({
      name: 'priceFrom',
      title: 'Starting Price',
      type: 'number',
      group: 'details',
      description: 'Lowest price point. Leave empty if pricing is custom.',
      validation: (Rule) => Rule.min(0),
    }),
    defineField({
      name: 'currency',
      title: 'Currency',
      type: 'string',
      group: 'details',
      initialValue: 'USD',
      options: {
        list: [
          { title: 'USD ($)', value: 'USD' },
          { title: 'EUR (\u20AC)', value: 'EUR' },
          { title: 'GBP (\u00A3)', value: 'GBP' },
        ],
      },
    }),
    defineField({
      name: 'isFeatured',
      title: 'Featured Service',
      description: 'Highlight this service on the homepage or listings.',
      type: 'boolean',
      group: 'details',
      initialValue: false,
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      group: 'details',
      of: [defineArrayMember({ type: 'string' })],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'launchDate',
      title: 'Launch Date',
      type: 'date',
      group: 'details',
    }),
    defineField({
      name: 'updatedAt',
      title: 'Last Updated',
      type: 'datetime',
      group: 'details',
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: 'relatedPage',
      title: 'Related Site Page',
      description: 'Link this service to a CMS-built page.',
      type: 'reference',
      group: 'details',
      to: [{ type: 'sitePage' }],
    }),
    defineField({
      name: 'officeLocation',
      title: 'Office Location',
      type: 'geopoint',
      group: 'details',
      description: 'Optional map pin for this service location.',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seoFields',
      group: 'seo',
    }),
  ],
  orderings: [
    {
      title: 'Featured First',
      name: 'featuredFirst',
      by: [
        { field: 'isFeatured', direction: 'desc' },
        { field: '_updatedAt', direction: 'desc' },
      ],
    },
    {
      title: 'Name (A-Z)',
      name: 'titleAsc',
      by: [{ field: 'title', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'summary',
      media: 'heroImage',
      featured: 'isFeatured',
    },
    prepare: ({ title, subtitle, media, featured }) => ({
      title: `${featured ? '* ' : ''}${title || 'Untitled Service'}`,
      subtitle: subtitle || '',
      media,
    }),
  },
});
