import { defineArrayMember, defineField, defineType } from 'sanity';
import { UsersIcon } from '@sanity/icons';
import { isSlugUniqueAcrossTypes } from './shared/slugValidation';

export const testimonial = defineType({
  name: 'testimonial',
  title: 'Testimonial',
  type: 'document',
  icon: UsersIcon,
  description: 'Customer quotes and reviews.',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'metadata', title: 'Details' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'personName',
      title: 'Name',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'role',
      title: 'Job Title',
      type: 'string',
      group: 'content',
      description: 'e.g. "CTO", "Head of Product"',
    }),
    defineField({
      name: 'company',
      title: 'Company',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'quote',
      title: 'Quote',
      description: 'The testimonial text shown on the site.',
      type: 'text',
      rows: 4,
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'avatar',
      title: 'Photo',
      type: 'image',
      group: 'content',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Alt text', type: 'string' })],
    }),
    defineField({
      name: 'rating',
      title: 'Rating',
      description: 'Star rating from 1 to 5.',
      type: 'number',
      group: 'content',
      initialValue: 5,
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: 'details',
      title: 'Extended Details',
      description: 'Optional longer testimonial content (not shown on listing cards).',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({ type: 'block' })],
    }),
    defineField({
      name: 'slug',
      title: 'URL Path',
      type: 'slug',
      group: 'metadata',
      options: { source: 'personName', isUnique: isSlugUniqueAcrossTypes },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'isFeatured',
      title: 'Featured',
      description: 'Show this testimonial prominently on the site.',
      type: 'boolean',
      group: 'metadata',
      initialValue: false,
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
      group: 'metadata',
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: 'relatedService',
      title: 'Related Service',
      description: 'Link to the service this testimonial is about.',
      type: 'reference',
      group: 'metadata',
      to: [{ type: 'serviceItem' }],
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      group: 'metadata',
      of: [defineArrayMember({ type: 'string' })],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'publishDate',
      title: 'Publish Date',
      type: 'date',
      group: 'metadata',
      hidden: true,
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seoFields',
      group: 'seo',
    }),
  ],
  orderings: [
    {
      title: 'Featured First',
      name: 'featuredFirst',
      by: [
        { field: 'isFeatured', direction: 'desc' },
        { field: '_updatedAt', direction: 'desc' },
      ],
    },
    {
      title: 'Name (A-Z)',
      name: 'nameAsc',
      by: [{ field: 'personName', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'personName',
      role: 'role',
      company: 'company',
      media: 'avatar',
      featured: 'isFeatured',
    },
    prepare: ({ title, role, company, media, featured }) => ({
      title: `${featured ? '* ' : ''}${title || 'Untitled Testimonial'}`,
      subtitle: [role, company].filter(Boolean).join(' at ') || 'Testimonial',
      media,
    }),
  },
});
