// Thin barrel — all implementation lives in ./cms/*
export type {
  AboutProfile,
  BlogCategory,
  BlogPost,
  CmsReadOptions,
  CollectionData,
  FrameworkEntry,
  InsightEntry,
  Logo,
  PageSection,
  RedirectRule,
  SeoFields,
  ServiceItem,
  SitemapQueryResult,
  SitePage,
  SiteSettings,
  SolutionEntry,
  TeamMember,
  Testimonial,
  UISettings,
} from './cms/types.ts';

export {
  getAboutProfileBySlug,
  getAboutProfiles,
  getBlogPostBySlug,
  getCollectionData,
  getFrameworkEntries,
  getFrameworkEntryBySlug,
  getInsightEntries,
  getInsightEntryBySlug,
  getServiceItemBySlug,
  getSitemapSlugs,
  getSitePageBySlug,
  getSiteSettings,
  getSolutionEntries,
  getSolutionEntryBySlug,
  getUISettings,
} from './cms/queries.ts';
