-- Auto-generated schema drift repair: 2026-04-04
-- Generated by: npm run db:schema:drift
-- Missing columns detected in the database.
-- All statements use ADD COLUMN IF NOT EXISTS (safe to re-run).
-- REVIEW before committing: verify types and defaults are correct.

BEGIN;

ALTER TABLE IF EXISTS public._ui_settings_v
  ADD COLUMN IF NOT EXISTS version_email_palette_primary character varying,
  ADD COLUMN IF NOT EXISTS version_email_palette_muted character varying,
  ADD COLUMN IF NOT EXISTS version_email_palette_text character varying,
  ADD COLUMN IF NOT EXISTS version_email_palette_background character varying,
  ADD COLUMN IF NOT EXISTS version_email_palette_white character varying,
  ADD COLUMN IF NOT EXISTS version_email_palette_border character varying,
  ADD COLUMN IF NOT EXISTS version_email_palette_error character varying;

ALTER TABLE IF EXISTS public._site_settings_v
  ADD COLUMN IF NOT EXISTS version_content_routing_guide_title character varying,
  ADD COLUMN IF NOT EXISTS version_content_routing_guide_pdf_url character varying,
  ADD COLUMN IF NOT EXISTS version_content_routing_guide_page_url character varying,
  ADD COLUMN IF NOT EXISTS version_content_routing_privacy_policy_url character varying,
  ADD COLUMN IF NOT EXISTS version_content_routing_workflow_notify_email character varying;

ALTER TABLE IF EXISTS public.audit_logs
  ADD COLUMN IF NOT EXISTS actor_id character varying;

COMMIT;