-- Auto-generated schema drift repair: 2026-04-05
-- Generated by: npm run db:schema:drift
-- Missing columns detected in the database.
-- Missing enum labels detected for managed enums.
-- All statements use ADD COLUMN IF NOT EXISTS (safe to re-run).
-- REVIEW before committing: verify types and defaults are correct.

BEGIN;

ALTER TABLE IF EXISTS public.page_drafts
  ADD COLUMN IF NOT EXISTS sections_locked boolean DEFAULT false;

COMMIT;