-- Auto-generated schema drift repair: 2026-04-06
-- Generated by: npm run db:schema:drift
-- Missing columns detected in the database.
-- Missing enum labels detected for managed enums.
-- All statements use ADD COLUMN IF NOT EXISTS (safe to re-run).
-- REVIEW before committing: verify types and defaults are correct.

BEGIN;

ALTER TABLE IF EXISTS public.legacy_hero
  ADD COLUMN IF NOT EXISTS section_label character varying;

ALTER TABLE IF EXISTS public.legacy_stage
  ADD COLUMN IF NOT EXISTS section_label character varying;

ALTER TABLE IF EXISTS public.legacy_cta
  ADD COLUMN IF NOT EXISTS section_label character varying;

COMMIT;