/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitGuideForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/inquiry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitInquiryForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/registration/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRegistrationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/registration/{publicId}/payment-confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitPaymentConfirmation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/templates/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createWorkspaceFormTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/live/{id}/create-preset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPresetFromLivePage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/drafts/{id}/create-preset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPresetFromDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/drafts/{id}/promote-to-live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["promoteDraftToLive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/playgrounds/{id}/create-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createDraftFromPlayground"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pages/playgrounds/{id}/create-preset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPresetFromPlayground"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/seed-site-pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["seedSitePages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContentPageBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/navigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContentNavigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/registration-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRegistrationSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/registration-submissions/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRegistrationSubmission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchRegistrationSubmissionStatus"];
        trace?: never;
    };
    "/v1/admin/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminSubmissionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/submissions/{id}/replay-side-effects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replaySubmissionSideEffects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIntegrationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @constant */
            ok: true;
            service: string;
            requestId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ReadyResponse: {
            ok: boolean;
            service: string;
            requestId: string;
            /** Format: date-time */
            timestamp: string;
            dependencies: {
                cms: {
                    ready: boolean;
                    error?: string | null;
                };
                database: {
                    credentialsConfigured: boolean;
                };
                persistence: {
                    requiredPersistenceTablesReady: boolean;
                    idempotencyAndOutboxPersistentStoreReady: boolean;
                    error?: string | null;
                };
            };
        };
        MetricsResponse: {
            service: string;
            uptimeSeconds: number;
            requestId: string;
            /** Format: date-time */
            timestamp: string;
            requests: {
                total: number;
                byMethod: {
                    [key: string]: number;
                };
                byStatus: {
                    [key: string]: number;
                };
                byPath: {
                    [key: string]: number;
                };
            };
            timing: {
                averageMs: number;
                maxMs: number;
            };
        };
        BackendErrorResponse: {
            /** @constant */
            success: false;
            /** @enum {string} */
            code: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "ALREADY_EXISTS" | "REGISTRATION_FULL" | "REGISTRATION_NOT_OPEN" | "REGISTRATION_CLOSED" | "TRANSITION_FORBIDDEN" | "MISSING_IDEMPOTENCY_KEY" | "RATE_LIMITED" | "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD" | "BACKEND_UNAVAILABLE" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR";
            message: string;
            status: number;
            requestId?: string;
            retryAfterSeconds?: number;
            details?: {
                [key: string]: unknown;
            };
            error?: string;
        };
        GuideSubmissionRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            templateId?: string | number;
        };
        InquirySubmissionRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            company?: string;
            challenge?: string;
        };
        /** @enum {string} */
        RegistrationStatus: "submitted" | "payment_pending" | "payment_confirmation_submitted" | "payment_confirmed" | "registration_confirmed" | "cancelled_rejected";
        RegistrationContactPreferences: {
            email?: boolean;
            sms?: boolean;
            phone?: boolean;
            /** @enum {string} */
            preferredChannel?: "email" | "sms" | "phone";
        };
        RegistrationSubmissionRequest: {
            eventId: string;
            name: string;
            /** Format: email */
            email: string;
            participantCount?: number;
            instrument?: string;
            ageGroup?: string;
            contactPreferences?: components["schemas"]["RegistrationContactPreferences"];
        };
        RegistrationStatusResponse: {
            status: components["schemas"]["RegistrationStatus"];
            userFacingReason?: string | null;
        };
        RegistrationSubmissionResponse: components["schemas"]["RegistrationStatusResponse"] & {
            /** @constant */
            success: true;
            /** Format: uuid */
            publicId: string;
        };
        PaymentConfirmationRequest: {
            payerName: string;
            /** @enum {string} */
            paymentMethod: "zelle" | "venmo";
            amount: number;
            /** Format: date-time */
            paymentDate: string;
            referenceNote?: string;
        };
        AdminStatusUpdateRequest: {
            status: components["schemas"]["RegistrationStatus"];
            internalReason?: string;
            userFacingReason?: string;
        };
        AdminRegistrationSubmission: {
            /** Format: uuid */
            publicId: string;
            eventId?: string | null;
            status: components["schemas"]["RegistrationStatus"];
            registrationPayload: {
                name?: string;
                /** Format: email */
                email?: string;
                participantCount?: number;
                instrument?: string;
                ageGroup?: string;
                contactPreferences?: components["schemas"]["RegistrationContactPreferences"];
            };
            paymentConfirmationPayload?: {
                payerName?: string;
                /** @enum {string} */
                paymentMethod?: "zelle" | "venmo";
                amount?: number;
                /** Format: date-time */
                paymentDate?: string;
                referenceNote?: string;
            } | null;
            internalReason?: string | null;
            userFacingReason?: string | null;
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AdminRegistrationSubmissionsListResponse: {
            items: components["schemas"]["AdminRegistrationSubmission"][];
            meta: {
                total: number;
                page: number;
                limit: number;
                totalPages: number;
                byStatus: {
                    [key: string]: number;
                };
            };
        };
        AdminRegistrationSubmissionDetailResponse: {
            submission: components["schemas"]["AdminRegistrationSubmission"];
        };
        FormSubmissionSuccessResponse: {
            /** @constant */
            success: true;
        };
        FormTemplateCreateRequest: {
            /** @enum {string} */
            templateKey: "guide" | "inquiry" | "newsletter";
        };
        FormTemplateRecord: {
            created: boolean;
            id: string | number;
            title: string;
        };
        WorkspaceFormTemplateResponse: {
            /** @constant */
            success: true;
            form: components["schemas"]["FormTemplateRecord"];
        };
        WorkspacePresetMetaInput: {
            name?: string;
            category?: string;
            description?: string;
            thumbnailId?: string;
            tags?: string[];
        };
        WorkspacePresetRecord: {
            id: string | number;
            name: string;
        };
        WorkspacePresetResponse: {
            /** @constant */
            success: true;
            preset: components["schemas"]["WorkspacePresetRecord"];
        };
        WorkspaceDraftRecord: {
            id: string | number;
            title: string;
        };
        WorkspaceDraftResponse: {
            /** @constant */
            success: true;
            draft: components["schemas"]["WorkspaceDraftRecord"];
        };
        WorkspaceLivePageRecord: {
            id: string | number;
            isNew: boolean;
            slug: string;
        };
        WorkspaceLivePageResponse: {
            /** @constant */
            success: true;
            livePage: components["schemas"]["WorkspaceLivePageRecord"];
        };
        WorkspaceCreateDraftRequest: {
            title?: string;
            targetSlug: string;
        };
        SearchResultItem: {
            id: string | number;
            collection: string;
            title: string;
            slug?: string;
            excerpt?: string;
            tags?: string[];
            isFeatured?: boolean;
        };
        SearchResponse: {
            results: components["schemas"]["SearchResultItem"][];
            meta: {
                total: number;
                page: number;
                limit: number;
                totalPages: number;
                requestId?: string;
            };
            facets: {
                collection: {
                    [key: string]: number;
                };
                tag: {
                    [key: string]: number;
                };
            };
        };
        SeedSuccessResponse: {
            [key: string]: unknown;
        };
        ContentPageSection: {
            id?: string;
            blockType: string;
        } & {
            [key: string]: unknown;
        };
        ContentPageResponse: {
            page: {
                id?: string;
                title?: string;
                slug?: string;
                /** @enum {string} */
                pageMode?: "builder" | "template";
                /** @enum {string} */
                templateKey?: "default" | "landing" | "article" | "product";
                /** @enum {string} */
                presetKey?: "custom" | "home" | "services" | "about" | "pricing" | "contact";
                hideNavbar?: boolean;
                hideFooter?: boolean;
                pageBackgroundColor?: string;
                sections: components["schemas"]["ContentPageSection"][];
            };
        };
        ContentNavigationLink: {
            id?: string;
            label?: string;
            href?: string;
            isVisible?: boolean;
            children?: {
                id?: string;
                label?: string;
                href?: string;
            }[];
        };
        HeaderButton: {
            id?: string;
            label?: string;
            href?: string;
            /** @enum {string} */
            variant?: "primary" | "ghost";
            isVisible?: boolean;
        };
        ContentNavigationResponse: {
            siteName?: string;
            navigationLinks: components["schemas"]["ContentNavigationLink"][];
            headerButtons: components["schemas"]["HeaderButton"][];
        };
        AdminSideEffects: {
            total: number;
            pending: number;
            retrying: number;
            succeeded: number;
            deadLetter: number;
            /** @enum {string} */
            status: "pending" | "retrying" | "succeeded" | "dead_letter";
        };
        AdminSubmission: {
            id: string;
            /** @enum {string} */
            kind: "guide" | "inquiry";
            name: string;
            /** Format: email */
            email: string;
            company?: string;
            challenge?: string;
            /** Format: date-time */
            submittedAt: string;
            sideEffects: components["schemas"]["AdminSideEffects"];
        };
        AdminSubmissionsListResponse: {
            items: components["schemas"]["AdminSubmission"][];
            meta: {
                total: number;
                page: number;
                limit: number;
                totalPages: number;
            };
        };
        OutboxJob: {
            id: string;
            provider: string;
            /** @enum {string} */
            status: "pending" | "processing" | "retrying" | "succeeded" | "dead_letter";
            attempts: number;
            maxAttempts: number;
            /** Format: date-time */
            nextAttemptAt?: string;
            lastError?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AdminSubmissionDetailResponse: {
            submission: components["schemas"]["AdminSubmission"];
            jobs: components["schemas"]["OutboxJob"][];
        };
        AdminReplaySubmissionResponse: {
            /** @constant */
            replayed: true;
            submissionId: string;
            enqueuedJobs: number;
        };
        IntegrationStatusResponse: {
            providers: {
                crmWebhook: {
                    configured: boolean;
                    urlConfigured: boolean;
                    secretConfigured: boolean;
                };
                resendEmail: {
                    configured: boolean;
                };
                outboundWebhook: {
                    configured: boolean;
                    signatureEnabled: boolean;
                };
            };
            persistence: {
                databaseCredentialsConfigured: boolean;
            };
        };
    };
    responses: {
        /** @description Input validation error. */
        ErrorValidation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Missing/invalid credentials. */
        ErrorUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Credential lacks required role/scope. */
        ErrorForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Resource not found. */
        ErrorNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Conflict (for example idempotency key mismatch). */
        ErrorConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Rate limit exceeded. */
        ErrorRateLimited: {
            headers: {
                /** @description Seconds until retry. */
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Internal server error. */
        ErrorInternal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Dependency is unavailable for this request. */
        ErrorDependencyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend liveness status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend readiness status and dependency checks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend request/latency metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
        };
    };
    searchContent: {
        parameters: {
            query?: {
                q?: string;
                collection?: "service-items" | "blog-posts" | "testimonials" | "site-pages";
                tag?: string;
                featured?: boolean;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search response with paginated results and facets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            429: components["responses"]["ErrorRateLimited"];
        };
    };
    submitGuideForm: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional key for safe retries of this POST operation. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuideSubmissionRequest"];
            };
        };
        responses: {
            /** @description Guide form accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormSubmissionSuccessResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            403: components["responses"]["ErrorForbidden"];
            409: components["responses"]["ErrorConflict"];
            429: components["responses"]["ErrorRateLimited"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    submitInquiryForm: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional key for safe retries of this POST operation. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InquirySubmissionRequest"];
            };
        };
        responses: {
            /** @description Inquiry form accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormSubmissionSuccessResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            403: components["responses"]["ErrorForbidden"];
            409: components["responses"]["ErrorConflict"];
            429: components["responses"]["ErrorRateLimited"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    submitRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationSubmissionRequest"];
            };
        };
        responses: {
            /** @description Registration submission accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationSubmissionResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            409: components["responses"]["ErrorConflict"];
            422: components["responses"]["ErrorValidation"];
            429: components["responses"]["ErrorRateLimited"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    getRegistrationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public registration status response (no public identifier or PII fields). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationStatusResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            404: components["responses"]["ErrorNotFound"];
            429: components["responses"]["ErrorRateLimited"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    submitPaymentConfirmation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentConfirmationRequest"];
            };
        };
        responses: {
            /** @description Payment confirmation accepted or replayed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationStatusResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
            429: components["responses"]["ErrorRateLimited"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    createWorkspaceFormTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormTemplateCreateRequest"];
            };
        };
        responses: {
            /** @description Form template was created or already existed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceFormTemplateResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            503: components["responses"]["ErrorDependencyUnavailable"];
        };
    };
    createPresetFromLivePage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string | number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WorkspacePresetMetaInput"];
            };
        };
        responses: {
            /** @description Preset created from a live page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePresetResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
            503: components["responses"]["ErrorDependencyUnavailable"];
        };
    };
    createPresetFromDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string | number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WorkspacePresetMetaInput"];
            };
        };
        responses: {
            /** @description Preset created from a draft. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePresetResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
            503: components["responses"]["ErrorDependencyUnavailable"];
        };
    };
    promoteDraftToLive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string | number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft promoted to live page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceLivePageResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
            503: components["responses"]["ErrorDependencyUnavailable"];
        };
    };
    createDraftFromPlayground: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string | number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreateDraftRequest"];
            };
        };
        responses: {
            /** @description Draft created from playground. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDraftResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
            503: components["responses"]["ErrorDependencyUnavailable"];
        };
    };
    createPresetFromPlayground: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string | number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WorkspacePresetMetaInput"];
            };
        };
        responses: {
            /** @description Preset created from a playground. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePresetResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
            503: components["responses"]["ErrorDependencyUnavailable"];
        };
    };
    seedSitePages: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seed finished successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedSuccessResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            404: components["responses"]["ErrorNotFound"];
            409: components["responses"]["ErrorConflict"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    getContentPageBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CMS page content by slug. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentPageResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            404: components["responses"]["ErrorNotFound"];
            429: components["responses"]["ErrorRateLimited"];
        };
    };
    getContentNavigation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Navigation and header button data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentNavigationResponse"];
                };
            };
            429: components["responses"]["ErrorRateLimited"];
        };
    };
    listRegistrationSubmissions: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: components["schemas"]["RegistrationStatus"];
                eventId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated registration submissions with status counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRegistrationSubmissionsListResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    getRegistrationSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registration submission detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRegistrationSubmissionDetailResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    patchRegistrationSubmissionStatus: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Registration status updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRegistrationSubmissionDetailResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
            409: components["responses"]["ErrorConflict"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    listAdminSubmissions: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of guide/inquiry submissions with side-effect status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSubmissionsListResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
        };
    };
    getAdminSubmissionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission detail and outbox job state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSubmissionDetailResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
        };
    };
    replaySubmissionSideEffects: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replay accepted and enqueued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReplaySubmissionResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
            409: components["responses"]["ErrorConflict"];
        };
    };
    getIntegrationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integration and persistence configuration status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
        };
    };
}
