/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/guide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitGuideForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forms/inquiry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitInquiryForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/seed-site-pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["seedSitePages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContentPageBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/content/navigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContentNavigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminSubmissionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/submissions/{id}/replay-side-effects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replaySubmissionSideEffects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIntegrationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @constant */
            ok: true;
            service: string;
            requestId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ReadyResponse: {
            ok: boolean;
            service: string;
            requestId: string;
            /** Format: date-time */
            timestamp: string;
            dependencies: {
                cms: {
                    ready: boolean;
                    error?: string | null;
                };
                database: {
                    credentialsConfigured: boolean;
                };
                persistence: {
                    idempotencyAndOutboxPersistentStoreReady: boolean;
                };
            };
        };
        MetricsResponse: {
            service: string;
            uptimeSeconds: number;
            requestId: string;
            /** Format: date-time */
            timestamp: string;
            requests: {
                total: number;
                byMethod: {
                    [key: string]: number;
                };
                byStatus: {
                    [key: string]: number;
                };
                byPath: {
                    [key: string]: number;
                };
            };
            timing: {
                averageMs: number;
                maxMs: number;
            };
        };
        BackendErrorResponse: {
            /** @constant */
            success: false;
            /** @enum {string} */
            code: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "RATE_LIMITED" | "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD" | "DEPENDENCY_UNAVAILABLE" | "INTERNAL_ERROR";
            message: string;
            status: number;
            requestId?: string;
            retryAfterSeconds?: number;
            details?: {
                [key: string]: unknown;
            };
            error?: string;
        };
        GuideSubmissionRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            templateId?: string | number;
        };
        InquirySubmissionRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            company?: string;
            challenge?: string;
        };
        FormSubmissionSuccessResponse: {
            /** @constant */
            success: true;
        };
        SearchResultItem: {
            id: string | number;
            collection: string;
            title: string;
            slug?: string;
            excerpt?: string;
            tags?: string[];
            isFeatured?: boolean;
        };
        SearchResponse: {
            results: components["schemas"]["SearchResultItem"][];
            meta: {
                total: number;
                page: number;
                limit: number;
                totalPages: number;
                requestId?: string;
            };
            facets: {
                collection: {
                    [key: string]: number;
                };
                tag: {
                    [key: string]: number;
                };
            };
        };
        SeedSuccessResponse: {
            [key: string]: unknown;
        };
        ContentPageSection: {
            id?: string;
            blockType: string;
        } & {
            [key: string]: unknown;
        };
        ContentPageResponse: {
            page: {
                id?: string;
                title?: string;
                slug?: string;
                /** @enum {string} */
                pageMode?: "builder" | "template";
                /** @enum {string} */
                templateKey?: "default" | "landing" | "article" | "product";
                /** @enum {string} */
                presetKey?: "custom" | "home" | "services" | "about" | "pricing" | "contact";
                hideNavbar?: boolean;
                hideFooter?: boolean;
                pageBackgroundColor?: string;
                sections: components["schemas"]["ContentPageSection"][];
            };
        };
        ContentNavigationLink: {
            id?: string;
            label?: string;
            href?: string;
            isVisible?: boolean;
            children?: {
                id?: string;
                label?: string;
                href?: string;
            }[];
        };
        HeaderButton: {
            id?: string;
            label?: string;
            href?: string;
            /** @enum {string} */
            variant?: "primary" | "ghost";
            isVisible?: boolean;
        };
        ContentNavigationResponse: {
            siteName?: string;
            navigationLinks: components["schemas"]["ContentNavigationLink"][];
            headerButtons: components["schemas"]["HeaderButton"][];
        };
        AdminSideEffects: {
            total: number;
            pending: number;
            retrying: number;
            succeeded: number;
            deadLetter: number;
            /** @enum {string} */
            status: "pending" | "retrying" | "succeeded" | "dead_letter";
        };
        AdminSubmission: {
            id: string;
            /** @enum {string} */
            kind: "guide" | "inquiry";
            name: string;
            /** Format: email */
            email: string;
            company?: string;
            challenge?: string;
            /** Format: date-time */
            submittedAt: string;
            sideEffects: components["schemas"]["AdminSideEffects"];
        };
        AdminSubmissionsListResponse: {
            items: components["schemas"]["AdminSubmission"][];
            meta: {
                total: number;
                page: number;
                limit: number;
                totalPages: number;
            };
        };
        OutboxJob: {
            id: string;
            provider: string;
            /** @enum {string} */
            status: "pending" | "processing" | "retrying" | "succeeded" | "dead_letter";
            attempts: number;
            maxAttempts: number;
            /** Format: date-time */
            nextAttemptAt?: string;
            lastError?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AdminSubmissionDetailResponse: {
            submission: components["schemas"]["AdminSubmission"];
            jobs: components["schemas"]["OutboxJob"][];
        };
        AdminReplaySubmissionResponse: {
            /** @constant */
            replayed: true;
            submissionId: string;
            enqueuedJobs: number;
        };
        IntegrationStatusResponse: {
            providers: {
                crmWebhook: {
                    configured: boolean;
                    urlConfigured: boolean;
                    secretConfigured: boolean;
                };
                resendEmail: {
                    configured: boolean;
                };
                outboundWebhook: {
                    configured: boolean;
                    signatureEnabled: boolean;
                };
            };
            persistence: {
                databaseCredentialsConfigured: boolean;
            };
        };
    };
    responses: {
        /** @description Input validation error. */
        ErrorValidation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Missing/invalid credentials. */
        ErrorUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Credential lacks required role/scope. */
        ErrorForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Resource not found. */
        ErrorNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Conflict (for example idempotency key mismatch). */
        ErrorConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Rate limit exceeded. */
        ErrorRateLimited: {
            headers: {
                /** @description Seconds until retry. */
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
        /** @description Internal server error. */
        ErrorInternal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BackendErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend liveness status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend readiness status and dependency checks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend request/latency metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
        };
    };
    searchContent: {
        parameters: {
            query?: {
                q?: string;
                collection?: "service-items" | "blog-posts" | "testimonials" | "site-pages";
                tag?: string;
                featured?: boolean;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search response with paginated results and facets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            429: components["responses"]["ErrorRateLimited"];
        };
    };
    submitGuideForm: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional key for safe retries of this POST operation. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuideSubmissionRequest"];
            };
        };
        responses: {
            /** @description Guide form accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormSubmissionSuccessResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            403: components["responses"]["ErrorForbidden"];
            409: components["responses"]["ErrorConflict"];
            429: components["responses"]["ErrorRateLimited"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    submitInquiryForm: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional key for safe retries of this POST operation. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InquirySubmissionRequest"];
            };
        };
        responses: {
            /** @description Inquiry form accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormSubmissionSuccessResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            403: components["responses"]["ErrorForbidden"];
            409: components["responses"]["ErrorConflict"];
            429: components["responses"]["ErrorRateLimited"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    seedSitePages: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seed finished successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedSuccessResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            404: components["responses"]["ErrorNotFound"];
            409: components["responses"]["ErrorConflict"];
            500: components["responses"]["ErrorInternal"];
        };
    };
    getContentPageBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CMS page content by slug. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentPageResponse"];
                };
            };
            400: components["responses"]["ErrorValidation"];
            404: components["responses"]["ErrorNotFound"];
            429: components["responses"]["ErrorRateLimited"];
        };
    };
    getContentNavigation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Navigation and header button data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentNavigationResponse"];
                };
            };
            429: components["responses"]["ErrorRateLimited"];
        };
    };
    listAdminSubmissions: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of guide/inquiry submissions with side-effect status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSubmissionsListResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
        };
    };
    getAdminSubmissionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission detail and outbox job state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSubmissionDetailResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
        };
    };
    replaySubmissionSideEffects: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replay accepted and enqueued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReplaySubmissionResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
            404: components["responses"]["ErrorNotFound"];
            409: components["responses"]["ErrorConflict"];
        };
    };
    getIntegrationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integration and persistence configuration status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationStatusResponse"];
                };
            };
            401: components["responses"]["ErrorUnauthorized"];
            403: components["responses"]["ErrorForbidden"];
        };
    };
}
