import type { MigrateDownArgs, MigrateUpArgs } from '@payloadcms/db-postgres';
import { sql } from '@payloadcms/db-postgres';

/**
 * Consolidate historical schema backfills into a versioned Payload migration.
 *
 * This replaces runtime schema patching so production schema changes remain
 * migration-driven and deterministic.
 */

const TABLE_STUBS_SQL = [
  "CREATE TABLE IF NOT EXISTS public.ui_settings (\n  id          serial      PRIMARY KEY,\n  _status     character varying DEFAULT 'draft',\n  created_at  timestamptz NOT NULL DEFAULT now(),\n  updated_at  timestamptz NOT NULL DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS public._ui_settings_v (\n  id              serial      PRIMARY KEY,\n  version__status character varying DEFAULT 'draft',\n  created_at      timestamptz NOT NULL DEFAULT now(),\n  updated_at      timestamptz NOT NULL DEFAULT now(),\n  latest          boolean\n);",
  "CREATE TABLE IF NOT EXISTS public.site_settings (\n  id          serial      PRIMARY KEY,\n  _status     character varying DEFAULT 'draft',\n  created_at  timestamptz NOT NULL DEFAULT now(),\n  updated_at  timestamptz NOT NULL DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS public._site_settings_v (\n  id              serial      PRIMARY KEY,\n  version__status character varying DEFAULT 'draft',\n  created_at      timestamptz NOT NULL DEFAULT now(),\n  updated_at      timestamptz NOT NULL DEFAULT now(),\n  latest          boolean\n);",
  "CREATE TABLE IF NOT EXISTS public.site_settings_navigation_links (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 1,\n  id         character varying PRIMARY KEY,\n  label      character varying,\n  href       character varying,\n  is_visible boolean DEFAULT true\n);",
  "CREATE TABLE IF NOT EXISTS public._site_settings_v_version_navigation_links (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 1,\n  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  label      character varying,\n  href       character varying,\n  is_visible boolean DEFAULT true,\n  _uuid      character varying\n);",
  "CREATE TABLE IF NOT EXISTS public.nav_children (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id character varying NOT NULL DEFAULT '',\n  id         character varying PRIMARY KEY,\n  label      character varying,\n  href       character varying\n);",
  "CREATE TABLE IF NOT EXISTS public._nav_children_v (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 1,\n  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  label      character varying,\n  href       character varying,\n  _uuid      character varying\n);",
  "CREATE TABLE IF NOT EXISTS public.form_submissions (\n  id          serial      PRIMARY KEY,\n  form_id     integer,\n  form_type   character varying,\n  created_at  timestamptz NOT NULL DEFAULT now(),\n  updated_at  timestamptz NOT NULL DEFAULT now()\n);",
  "CREATE TABLE IF NOT EXISTS public.richtext (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 0,\n  _path      text NOT NULL DEFAULT '',\n  id         character varying PRIMARY KEY\n);",
  "CREATE TABLE IF NOT EXISTS public.cta (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 0,\n  _path      text NOT NULL DEFAULT '',\n  id         character varying PRIMARY KEY\n);",
  "CREATE TABLE IF NOT EXISTS public.privacy_note (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 0,\n  _path      text NOT NULL DEFAULT '',\n  id         character varying PRIMARY KEY\n);",
  "CREATE TABLE IF NOT EXISTS public.vid_sec (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 0,\n  _path      text NOT NULL DEFAULT '',\n  id         character varying PRIMARY KEY\n);",
  "CREATE TABLE IF NOT EXISTS public.simple_table (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 0,\n  _path      text NOT NULL DEFAULT '',\n  id         character varying PRIMARY KEY\n);",
  "CREATE TABLE IF NOT EXISTS public.cmp_table (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 0,\n  _path      text NOT NULL DEFAULT '',\n  id         character varying PRIMARY KEY\n);",
  "CREATE TABLE IF NOT EXISTS public.dyn_list (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 0,\n  _path      text NOT NULL DEFAULT '',\n  id         character varying PRIMARY KEY\n);",
  "CREATE TABLE IF NOT EXISTS public.reuse_sec_ref (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 0,\n  _path      text NOT NULL DEFAULT '',\n  id         character varying PRIMARY KEY\n);",
  "CREATE TABLE IF NOT EXISTS public.divider (\n  _order     integer NOT NULL DEFAULT 0,\n  _parent_id integer NOT NULL DEFAULT 0,\n  _path      text NOT NULL DEFAULT '',\n  id         character varying PRIMARY KEY\n);"
] as const;

const MANIFEST_COLUMNS = {
  "hero": {
    "section_label": "character varying"
  },
  "richtext": {
    "section_label": "character varying"
  },
  "cta": {
    "section_label": "character varying"
  },
  "stats_sec": {
    "section_label": "character varying"
  },
  "faq_sec": {
    "section_label": "character varying"
  },
  "feat_grid": {
    "section_label": "character varying"
  },
  "form_sec": {
    "section_label": "character varying"
  },
  "team_sec": {
    "section_label": "character varying"
  },
  "logo_band": {
    "section_label": "character varying"
  },
  "quote_sec": {
    "section_label": "character varying"
  },
  "tabs_sec": {
    "section_label": "character varying"
  },
  "privacy_note": {
    "section_label": "character varying"
  },
  "img_sec": {
    "section_label": "character varying"
  },
  "vid_sec": {
    "section_label": "character varying"
  },
  "simple_table": {
    "section_label": "character varying"
  },
  "cmp_table": {
    "section_label": "character varying"
  },
  "dyn_list": {
    "section_label": "character varying"
  },
  "split_sec": {
    "section_label": "character varying"
  },
  "reuse_sec_ref": {
    "section_label": "character varying"
  },
  "divider": {
    "section_label": "character varying"
  },
  "service_items": {
    "created_by_id": "integer",
    "submitted_by_id": "integer",
    "submitted_at": "timestamptz"
  },
  "blog_posts": {
    "created_by_id": "integer",
    "submitted_by_id": "integer",
    "submitted_at": "timestamptz"
  },
  "testimonials": {
    "created_by_id": "integer",
    "name": "character varying",
    "submitted_by_id": "integer",
    "submitted_at": "timestamptz"
  },
  "site_pages": {
    "created_by_id": "integer",
    "submitted_by_id": "integer",
    "submitted_at": "timestamptz"
  },
  "page_drafts": {
    "deleted_at": "timestamptz",
    "workflow_status": "character varying DEFAULT 'draft'",
    "submitted_by_id": "integer",
    "submitted_at": "timestamptz",
    "review_checklist_complete": "boolean DEFAULT false",
    "review_summary": "text",
    "approved_by_id": "integer",
    "approved_at": "timestamptz",
    "rejection_reason": "text",
    "created_by_id": "integer",
    "target_slug": "character varying",
    "source_type": "character varying",
    "source_page_id": "integer",
    "source_preset_id": "integer",
    "source_playground_id": "integer",
    "editor_notes": "text",
    "seo_meta_title": "character varying",
    "seo_meta_description": "character varying",
    "seo_og_title": "character varying",
    "seo_og_description": "character varying",
    "seo_og_image_id": "integer",
    "seo_canonical_url": "character varying",
    "seo_noindex": "boolean DEFAULT false",
    "seo_nofollow": "boolean DEFAULT false",
    "seo_include_in_sitemap": "boolean DEFAULT false",
    "sections_locked": "boolean DEFAULT false"
  },
  "page_presets": {
    "created_by_id": "integer",
    "name": "character varying",
    "category": "character varying",
    "description": "text",
    "thumbnail_id": "integer",
    "structure_mode": "character varying",
    "source_type": "character varying",
    "source_live_page_id": "integer",
    "source_draft_id": "integer",
    "created_from_snapshot_at": "timestamptz"
  },
  "page_playgrounds": {
    "created_by_id": "integer",
    "name": "character varying",
    "visibility": "character varying",
    "notes": "text"
  },
  "blog_categories": {
    "deleted_at": "timestamptz",
    "workflow_status": "character varying DEFAULT 'draft'",
    "submitted_by_id": "integer",
    "submitted_at": "timestamptz",
    "review_checklist_complete": "boolean DEFAULT false",
    "review_summary": "text",
    "approved_by_id": "integer",
    "approved_at": "timestamptz",
    "rejection_reason": "text"
  },
  "team_members": {
    "deleted_at": "timestamptz",
    "workflow_status": "character varying DEFAULT 'draft'",
    "submitted_by_id": "integer",
    "submitted_at": "timestamptz",
    "review_checklist_complete": "boolean DEFAULT false",
    "review_summary": "text",
    "approved_by_id": "integer",
    "approved_at": "timestamptz",
    "rejection_reason": "text",
    "linkedin_url": "character varying",
    "twitter_url": "character varying"
  },
  "logos": {
    "deleted_at": "timestamptz",
    "workflow_status": "character varying DEFAULT 'draft'",
    "submitted_by_id": "integer",
    "submitted_at": "timestamptz",
    "review_checklist_complete": "boolean DEFAULT false",
    "review_summary": "text",
    "approved_by_id": "integer",
    "approved_at": "timestamptz",
    "rejection_reason": "text",
    "url": "character varying"
  },
  "ui_settings": {
    "colors_nav_background": "character varying DEFAULT 'transparent'",
    "colors_nav_scrolled_background": "character varying DEFAULT '#FFFFFF'",
    "colors_nav_border": "character varying DEFAULT '#E5E7EB'",
    "typography_heading_font_url": "character varying",
    "typography_body_font_url": "character varying",
    "layout_nav_height": "numeric DEFAULT 68",
    "layout_card_radius": "numeric DEFAULT 8",
    "email_palette_primary": "character varying",
    "email_palette_muted": "character varying",
    "email_palette_text": "character varying",
    "email_palette_background": "character varying",
    "email_palette_white": "character varying",
    "email_palette_border": "character varying",
    "email_palette_error": "character varying"
  },
  "_ui_settings_v": {
    "version_colors_nav_background": "character varying DEFAULT 'transparent'",
    "version_colors_nav_scrolled_background": "character varying DEFAULT '#FFFFFF'",
    "version_colors_nav_border": "character varying DEFAULT '#E5E7EB'",
    "version_typography_heading_font_url": "character varying",
    "version_typography_body_font_url": "character varying",
    "version_layout_nav_height": "numeric DEFAULT 68",
    "version_layout_card_radius": "numeric DEFAULT 8",
    "version_email_palette_primary": "character varying",
    "version_email_palette_muted": "character varying",
    "version_email_palette_text": "character varying",
    "version_email_palette_background": "character varying",
    "version_email_palette_white": "character varying",
    "version_email_palette_border": "character varying",
    "version_email_palette_error": "character varying"
  },
  "site_settings": {
    "logo_image_id": "integer",
    "logo_width": "numeric DEFAULT 120",
    "announcement_banner_enabled": "boolean DEFAULT false",
    "announcement_banner_text": "character varying",
    "announcement_banner_link_label": "character varying",
    "announcement_banner_link_href": "character varying",
    "announcement_banner_background_color": "character varying DEFAULT '#1B2D4F'",
    "announcement_banner_text_color": "character varying DEFAULT '#FFFFFF'",
    "guide_form_privacy_label": "character varying DEFAULT 'Privacy Policy'",
    "guide_form_privacy_href": "character varying DEFAULT '/privacy'",
    "inquiry_form_privacy_label": "character varying DEFAULT 'Privacy Policy'",
    "inquiry_form_privacy_href": "character varying DEFAULT '/privacy'",
    "not_found_page_meta_title": "character varying DEFAULT 'Page Not Found'",
    "not_found_page_meta_description": "character varying DEFAULT 'The page you requested could not be found.'",
    "content_routing_guide_title": "character varying",
    "content_routing_guide_pdf_url": "character varying",
    "content_routing_guide_page_url": "character varying",
    "content_routing_privacy_policy_url": "character varying",
    "content_routing_workflow_notify_email": "character varying",
    "email_defaults_brand_name": "character varying",
    "email_defaults_guide_subject": "character varying",
    "email_defaults_guide_heading": "character varying",
    "email_defaults_guide_body": "text",
    "email_defaults_guide_button_label": "character varying",
    "email_defaults_inquiry_notification_subject": "character varying",
    "email_defaults_inquiry_ack_subject": "character varying",
    "email_defaults_inquiry_ack_heading": "character varying",
    "email_defaults_inquiry_ack_body": "text",
    "core_preset_content_home": "jsonb DEFAULT '{}'::jsonb",
    "core_preset_content_services": "jsonb DEFAULT '{}'::jsonb",
    "core_preset_content_about": "jsonb DEFAULT '{}'::jsonb",
    "core_preset_content_pricing": "jsonb DEFAULT '{}'::jsonb",
    "core_preset_content_contact": "jsonb DEFAULT '{}'::jsonb"
  },
  "_site_settings_v": {
    "version_logo_image_id": "integer",
    "version_logo_width": "numeric DEFAULT 120",
    "version_announcement_banner_enabled": "boolean DEFAULT false",
    "version_announcement_banner_text": "character varying",
    "version_announcement_banner_link_label": "character varying",
    "version_announcement_banner_link_href": "character varying",
    "version_announcement_banner_background_color": "character varying DEFAULT '#1B2D4F'",
    "version_announcement_banner_text_color": "character varying DEFAULT '#FFFFFF'",
    "version_guide_form_privacy_label": "character varying DEFAULT 'Privacy Policy'",
    "version_guide_form_privacy_href": "character varying DEFAULT '/privacy'",
    "version_inquiry_form_privacy_label": "character varying DEFAULT 'Privacy Policy'",
    "version_inquiry_form_privacy_href": "character varying DEFAULT '/privacy'",
    "version_not_found_page_meta_title": "character varying DEFAULT 'Page Not Found'",
    "version_not_found_page_meta_description": "character varying DEFAULT 'The page you requested could not be found.'",
    "version_content_routing_guide_title": "character varying",
    "version_content_routing_guide_pdf_url": "character varying",
    "version_content_routing_guide_page_url": "character varying",
    "version_content_routing_privacy_policy_url": "character varying",
    "version_content_routing_workflow_notify_email": "character varying",
    "version_email_defaults_brand_name": "character varying",
    "version_email_defaults_guide_subject": "character varying",
    "version_email_defaults_guide_heading": "character varying",
    "version_email_defaults_guide_body": "text",
    "version_email_defaults_guide_button_label": "character varying",
    "version_email_defaults_inquiry_notification_subject": "character varying",
    "version_email_defaults_inquiry_ack_subject": "character varying",
    "version_email_defaults_inquiry_ack_heading": "character varying",
    "version_email_defaults_inquiry_ack_body": "text",
    "version_core_preset_content_home": "jsonb DEFAULT '{}'::jsonb",
    "version_core_preset_content_services": "jsonb DEFAULT '{}'::jsonb",
    "version_core_preset_content_about": "jsonb DEFAULT '{}'::jsonb",
    "version_core_preset_content_pricing": "jsonb DEFAULT '{}'::jsonb",
    "version_core_preset_content_contact": "jsonb DEFAULT '{}'::jsonb"
  },
  "forms": {
    "template_key": "character varying",
    "email_template_id": "integer"
  },
  "form_submissions": {
    "form_type": "character varying"
  },
  "audit_logs": {
    "actor_id": "character varying",
    "ip_address": "character varying",
    "field_path": "character varying",
    "old_value_summary": "text",
    "new_value_summary": "text",
    "risk_tier": "character varying DEFAULT 'routine'"
  },
  "reuse_sec": {
    "library_category": "character varying DEFAULT 'general'",
    "library_version": "numeric DEFAULT 1",
    "library_change_summary": "text",
    "is_deprecated": "boolean DEFAULT false",
    "locale": "character varying DEFAULT 'en'",
    "translation_group_id": "character varying",
    "workflow_status": "character varying DEFAULT 'draft'",
    "submitted_by_id": "integer",
    "submitted_at": "timestamptz",
    "review_checklist_complete": "boolean DEFAULT false",
    "review_summary": "text",
    "approved_by_id": "integer",
    "approved_at": "timestamptz",
    "rejection_reason": "text"
  },
  "nav_children": {
    "label": "character varying",
    "href": "character varying"
  },
  "_nav_children_v": {
    "label": "character varying",
    "href": "character varying",
    "_uuid": "character varying"
  }
} as const;

const MANIFEST_ENUMS = {
  "public.enum_payload_query_presets_related_collection": [
    "users",
    "media",
    "forms",
    "service-items",
    "site-pages",
    "reusable-sections",
    "redirect-rules",
    "blog-posts",
    "testimonials",
    "blog-categories",
    "team-members",
    "logos",
    "page-drafts",
    "page-presets",
    "page-playgrounds"
  ]
} as const;

function quoteIdentifier(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function quoteLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

export async function up({ db }: MigrateUpArgs): Promise<void> {
  for (const statement of TABLE_STUBS_SQL) {
    await db.execute(sql.raw(statement));
  }

  for (const [qualifiedTypeName, labels] of Object.entries(MANIFEST_ENUMS)) {
    const [schema, ...rest] = qualifiedTypeName.split('.');
    if (!schema || rest.length === 0) {
      throw new Error(`Invalid enum type name: ${qualifiedTypeName}`);
    }

    const name = rest.join('.');
    const qualifiedTypeIdentifier = `${quoteIdentifier(schema)}.${quoteIdentifier(name)}`;
    const enumValuesSql = labels.map((label) => quoteLiteral(label)).join(', ');

    await db.execute(sql.raw(`
DO $$
BEGIN
  CREATE TYPE ${qualifiedTypeIdentifier} AS ENUM (${enumValuesSql});
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;
    `));

    for (const label of labels) {
      await db.execute(
        sql.raw(`ALTER TYPE ${qualifiedTypeIdentifier} ADD VALUE IF NOT EXISTS ${quoteLiteral(label)};`),
      );
    }
  }

  for (const [tableName, columns] of Object.entries(MANIFEST_COLUMNS)) {
    const addClauses = Object.entries(columns).map(
      ([columnName, columnDefinition]) =>
        `ADD COLUMN IF NOT EXISTS ${quoteIdentifier(columnName)} ${columnDefinition}`,
    );

    if (addClauses.length === 0) continue;

    await db.execute(sql.raw(`
      ALTER TABLE IF EXISTS ${quoteIdentifier('public')}.${quoteIdentifier(tableName)}
        ${addClauses.join(',\n        ')};
    `));
  }
}

// This migration is additive and intended as a one-way repair for drifted envs.
export async function down({}: MigrateDownArgs): Promise<void> {}
